name = "ResizableArrays"
uuid = "df514bf8-98b6-11e9-19f1-af1e340ea726"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.3.3"

[deps]
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"

[compat]
julia = "1"
ArrayTools = "0.2.3, 0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
