name = "ResizableArrays"
uuid = "df514bf8-98b6-11e9-19f1-af1e340ea726"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.2.0"

[compat]
julia = "1.0, 1.1, 1.2, 1.3, 1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
